;;; cond-let-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from git-spice.el

(autoload 'git-spice-setup-magit-section "git-spice" "\
Enable git-spice section in Magit status buffer." t)
 (autoload 'git-spice-menu "git-spice" nil t)
(register-definition-prefixes "git-spice" '("git-spice-"))

;;; End of scraped data

(provide 'cond-let-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; cond-let-autoloads.el ends here
